quarkus.http.port=${PORT:8080}
quarkus.jackson.accept-case-insensitive-enums=true
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${POSTGRES_USER:mitocodequarkusdbuser}
quarkus.datasource.password=${POSTGRES_PASSWORD:Java360445}
# URL REACTIVA
quarkus.datasource.reactive.url=${URL_DATABASE:postgresql://postgres-mitocode-26-4:5432/mitocodedb2026_4?sslmode=disable}
quarkus.datasource.reactive.max-size=20
# URL JDBC
quarkus.datasource.jdbc.url=jdbc:${URL_DATABASE:postgresql://postgres-mitocode-26-4:5432/mitocodedb2026_4?sslmode=disable}
quarkus.hibernate-orm.database.generation=none
# --------------- CONFIGURACI�N FLYWAY --------------------
# Activar la migraci�n autom�tica al iniciar la app
quarkus.flyway.migrate-at-start=true

# 1. Define el nombre de tu esquema
quarkus.flyway.schemas=reservedb

# 2. Obliga a Flyway a crear el es:quema si no existe
quarkus.flyway.create-schemas=true

# 3. Le dice a Hibernate que use ese esquema por defecto,
# de lo contrario Hibernate seguir� buscando las tablas en public
quarkus.hibernate-orm.database.default-schema=reservedb

# ----------------------------------------------------------