quarkus.http.port=8083
geocoding.api.url=https://nominatim.openstreetmap.org
quarkus.jackson.accept-case-insensitive-enums=true

# --- CONFIGURACIÓN BASE DE DATOS ---
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=mitocodequarkusdbuser
quarkus.datasource.password=Java360445
# URL REACTIVA
quarkus.datasource.reactive.url=postgresql://localhost:5432/mitocodedb2026_4?sslmode=disable
quarkus.datasource.reactive.max-size=20
# -- JDBC URL --
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/mitocodedb2026_4?sslmode=disable
quarkus.hibernate-orm.database.generation=none
# -----------------------------------------------------------

# --------------- CONFIGURACIÓN FLYWAY ----------------------
# Activar la migración automática al iniciar la app
quarkus.flyway.migrate-at-start=true

# 1. Define el nombre de tu esquema
quarkus.flyway.schemas=reservedb

# 2. Obliga a Flyway a crear el esquema si no existe
quarkus.flyway.create-schemas=true

# 3. Le dice a Hibernate que use ese esquema por defecto,
# de lo contrario Hibernate seguirá buscando las tablas en public
quarkus.hibernate-orm.database.default-schema=reservedb

# ----------------------------------------------------------

